# Generated by Django 5.0.14 on 2026-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Hakkımda'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Saatlik Ücret (₺)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Doğrulanmış Eğitmen'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/teachers/', verbose_name='Profil Fotoğrafı'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Uzmanlık Ünvanı'),
        ),
    ]
