# Generated by Django 5.0.14 on 2026-08-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_parentlinkrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Aktif Abonelik'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='revenuecat_app_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='RevenueCat Kullanıcı ID'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Abonelik Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subscription_platform',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Abonelik Platformu (stripe/app_store/play_store)'),
        ),
    ]
