# Generated by Django 5.0.14 on 2026-08-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_teacherprofile_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subscription_exempt',
            field=models.BooleanField(default=False, verbose_name='Admin Tarafından Ücretsiz Erişim Verildi'),
        ),
    ]
