databases:
  - name: edutracker-db
    plan: free
    databaseName: edutracker
    user: edutracker

services:
  - type: web
    name: edutracker-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: edutracker-db
          property: connectionString
