# Generated by Django 5.0.14 on 2026-07-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ders/Konu Adı')),
                ('grade_level', models.IntegerField(blank=True, null=True, verbose_name='Sınıf Seviyesi (Örn: 10)')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Öğrenci')),
                ('started_at', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors_list', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_list', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Özel Ders Bağlantısı',
                'verbose_name_plural': 'Özel Ders Bağlantıları',
                'unique_together': {('tutor', 'student', 'subject')},
            },
        ),
    ]
