# Generated by Django 5.0.14 on 2026-07-19 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ödev Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('due_date', models.DateTimeField(verbose_name='Son Teslim Tarihi')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('COMPLETED', 'Tamamlandı'), ('LATE', 'Gecikti')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.tutoringrelation')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200, verbose_name='Sınav/Konu Adı')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puan/Net')),
                ('exam_date', models.DateField(verbose_name='Sınav Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Öğretmen Notu')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.tutoringrelation')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kaynak Başlığı')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link (Opsiyonel)')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Dosya (Opsiyonel)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='school.tutoringrelation')),
            ],
        ),
    ]
